package codegen

import (
	"bytes"
	"embed"
	"fmt"
	"path"
	"text/template"
)

//go:embed templates
var templateFS embed.FS

// AgentRoles is the ordered list of roles generated by init.
var AgentRoles = []string{"architect", "developer", "qa", "pr-reviewer", "security-reviewer", "analyst", "scribe"}

// AgentTemplateData holds variables substituted into agent templates.
type AgentTemplateData struct {
	ProjectName    string
	Language       string
	BuildTool      string
	TestCommand    string
	ProjectContext string
	Structure      string
}

// LoadTemplate reads the template for role in lang, falling back to "base" when
// no language-specific template is found. Returns an error only when neither
// lang nor base has a template for the role.
func LoadTemplate(lang, role string) (string, error) {
	p := path.Join("templates", lang, role+".md")
	data, err := templateFS.ReadFile(p)
	if err == nil {
		return string(data), nil
	}
	base := path.Join("templates", "base", role+".md")
	data, err = templateFS.ReadFile(base)
	if err != nil {
		return "", fmt.Errorf("codegen.LoadTemplate: no template for role %q in lang %q or base", role, lang)
	}
	return string(data), nil
}

// RenderTemplate applies data to a Go text/template string.
func RenderTemplate(tmplContent string, data AgentTemplateData) (string, error) {
	t, err := template.New("agent").Parse(tmplContent)
	if err != nil {
		return "", fmt.Errorf("codegen.RenderTemplate: parse: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("codegen.RenderTemplate: execute: %w", err)
	}
	return buf.String(), nil
}
