package codegen

import (
	"bytes"
	"embed"
	"fmt"
	"path"
	"text/template"
)

//go:embed templates
var templateFS embed.FS

// AgentRoles is the ordered list of roles generated by init.
var AgentRoles = []string{"architect", "developer", "qa", "pr-reviewer", "security-reviewer", "analyst", "scribe"}

// AgentTemplateData holds variables substituted into agent templates.
type AgentTemplateData struct {
	ProjectName    string
	Language       string
	BuildTool      string
	TestCommand    string
	ProjectContext string
	Structure      string
}

// LoadTemplate reads the generic base body template for role. The lang argument
// is retained for call-site compatibility and lookup order, but no per-language
// body templates exist anymore — language specialization lives in the runtime
// overlay (see LangOverlay). For any known role this therefore resolves the
// base/ template regardless of lang; it errors only when base has no template
// for the role. The base lookup still runs after a lang-specific probe that no
// longer matches, so the fallback path is exercised for every language.
func LoadTemplate(lang, role string) (string, error) {
	p := path.Join("templates", lang, role+".md")
	data, err := templateFS.ReadFile(p)
	if err == nil {
		return string(data), nil
	}
	base := path.Join("templates", "base", role+".md")
	data, err = templateFS.ReadFile(base)
	if err != nil {
		return "", fmt.Errorf("codegen.LoadTemplate: no template for role %q in lang %q or base", role, lang)
	}
	return string(data), nil
}

// RenderTemplate applies data to a Go text/template string.
func RenderTemplate(tmplContent string, data AgentTemplateData) (string, error) {
	t, err := template.New("agent").Parse(tmplContent)
	if err != nil {
		return "", fmt.Errorf("codegen.RenderTemplate: parse: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("codegen.RenderTemplate: execute: %w", err)
	}
	return buf.String(), nil
}
