package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/carlosneir4/tu-agent/internal/codegen"
)

const (
	knowledgeOpen  = "<!-- tu-agent:knowledge -->"
	knowledgeClose = "<!-- /tu-agent:knowledge -->"

	projectContextOpen  = "<!-- tu-agent:project-context -->"
	projectContextClose = "<!-- /tu-agent:project-context -->"
)

const knowledgeBody = knowledgeOpen + "\n" +
	"> Auto-generated by `tu-agent learn` — rewritten on each run. Put your own\n" +
	"> project instructions OUTSIDE the tu-agent:knowledge markers so they survive.\n" +
	"\n" +
	"## GROUNDWORK\n" +
	"- Non-trivial change (new file, feature, flow, tests) → invoke the `groundwork` skill FIRST.\n" +
	"- Skip only for: one-line edits, renames, formatting, reverts, reading, pure questions.\n" +
	"- Substantial feature → `groundwork` hands off to the `tdd` dev-flow.\n" +
	"\n" +
	"## PROTOCOL — graph first\n" +
	"| Trigger | Do FIRST |\n" +
	"|---|---|\n" +
	"| Before editing ANY file | `get_context(<file-or-symbol>)` |\n" +
	"| Impact / dependencies / callers / \"what breaks if I change X\" | `get_impact`, `get_context` |\n" +
	"| Where does a symbol live | `find_symbol` (grep only to cross-check a miss) |\n" +
	"| Structural question / how an area works | `get_architecture`, `get_concept` |\n" +
	"\n" +
	"- Graph tools are often DEFERRED: load them with ToolSearch (\"tu-agent-graph\");\n" +
	"  never conclude they are unavailable. CLI fallback: `tu-agent graph context <x>`.\n" +
	"- Graph says \"(none)\" for a symbol you can see used → it misses framework/DI\n" +
	"  links; cross-check with a targeted search.\n" +
	"- Graph contradicts code you can see → stale: run `tu-agent learn`, re-query.\n" +
	"- Read source files only AFTER the graph answered.\n" +
	"\n" +
	"## MEMORY\n" +
	"- Session start → `mem_recent`; before non-trivial work → `mem_search <area>`.\n" +
	"- Decision made / bug-pattern hit / non-trivial work finished → `mem_save`\n" +
	"  (`decision/...`, `bug-pattern/...` topics; the durable \"why\", not session chatter).\n" +
	"- A gotcha is its OWN note (`type: gotcha`, one trap per note) — never a section\n" +
	"  buried inside another note.\n" +
	"- Recall all traps: `memory search --type gotcha`.\n" +
	"- Note shape — bug-pattern/gotcha: Symptom → Root cause → Fix → Prevention (lead\n" +
	"  with the symptom); decision: Decision → Why → Alternatives rejected → Scope.\n" +
	"- Name code symbols in prose, never hand-list files (`memory relink` derives links).\n" +
	"- After `git pull` → `tu-agent memory import`.\n" +
	"\n" +
	"## VERIFY before claiming done\n" +
	"- Before reporting complete/fixed/passing → run the project's test command and\n" +
	"  report the ACTUAL output. Evidence before assertions (full discipline:\n" +
	"  verification-before-completion skill; in-app proof: verify-in-env).\n" +
	"\n" +
	"## Communication — explain plainly\n" +
	"- Audience: a strong engineer, English possibly second language, who does NOT\n" +
	"  know this codebase's terms, your acronyms, or idioms.\n" +
	"- Lead with the answer in 1-2 sentences; details after.\n" +
	"- Gloss every acronym/jargon/coined name on first use: \"surplus (fields\n" +
	"  produced but never consumed)\". Once glossed, reuse freely.\n" +
	"- One idea per sentence. A concrete snippet beats an abstract explanation.\n" +
	"- No idioms, no metaphors, no filler. Unsure whether a term is jargon → gloss it.\n" +
	knowledgeClose

// upsertMarkedBlock inserts or replaces the region between open/close markers in
// the file at mdPath with body. Idempotent: re-running yields an identical file.
// Creates the file (containing just body) if it does not exist.
func upsertMarkedBlock(mdPath, open, close, body string) error {
	existing, err := os.ReadFile(mdPath)
	if err != nil {
		if !os.IsNotExist(err) {
			return fmt.Errorf("upsertMarkedBlock: read %s: %w", mdPath, err)
		}
		if werr := os.WriteFile(mdPath, []byte(body+"\n"), 0o644); werr != nil {
			return fmt.Errorf("upsertMarkedBlock: create %s: %w", mdPath, werr)
		}
		return nil
	}
	var out string
	if start, end, found := codegen.FindMarkedRegion(string(existing), open, close); found {
		out = string(existing)[:start] + body + string(existing)[end:]
	} else {
		out = strings.TrimRight(string(existing), "\n") + "\n\n" + body + "\n"
	}
	if err := os.WriteFile(mdPath, []byte(out), 0o644); err != nil {
		return fmt.Errorf("upsertMarkedBlock: write %s: %w", mdPath, err)
	}
	return nil
}

// writeKnowledgeBlock inserts or replaces the tu-agent knowledge-pointer block.
func writeKnowledgeBlock(mdPath string) error {
	return upsertMarkedBlock(mdPath, knowledgeOpen, knowledgeClose, knowledgeBody)
}
