package main

import (
	"fmt"
	"os"
	"regexp"
	"strings"
)

const (
	knowledgeOpen  = "<!-- tu-agent:knowledge -->"
	knowledgeClose = "<!-- /tu-agent:knowledge -->"

	projectContextOpen  = "<!-- tu-agent:project-context -->"
	projectContextClose = "<!-- /tu-agent:project-context -->"
)

const knowledgeBody = knowledgeOpen + "\n" +
	"> Auto-generated by `tu-agent learn` — rewritten on each run. Put your own\n" +
	"> project instructions OUTSIDE the tu-agent:knowledge markers so they survive.\n" +
	"\n" +
	"This repo has tu-agent knowledge: an `architecture` skill in .claude/skills/,\n" +
	"concept cards in the graph store (via get_concept), and a dependency graph,\n" +
	"queryable via the graph tools (get_context, get_impact, find_symbol, get_concept)\n" +
	"or the `tu-agent graph` CLI.\n" +
	"\n" +
	"## GROUNDWORK — anchor & confirm before you build\n" +
	"Before creating a file, implementing a feature or flow, writing tests, or any\n" +
	"non-trivial change, invoke the `groundwork` skill FIRST — do not start from\n" +
	"assumptions. It makes you (1) anchor in the graph + memory (get_context,\n" +
	"mem_search) and load any project skill for the area, (2) ask the human only the\n" +
	"gaps the code cannot answer, (3) confirm the approach, (4) build incrementally,\n" +
	"(5) capture new gotchas/decisions as atomic notes. Skip only for one-line edits,\n" +
	"renames, formatting, reverts, reading, or pure questions. For a substantial\n" +
	"feature, the `groundwork` skill hands off to the `tdd` dev-flow.\n" +
	"\n" +
	"## PROTOCOL — follow before answering structural questions or editing\n" +
	"1. Orient: skim the `architecture` skill; get a concept's meaning with get_concept\n" +
	"   (or get_context), which read from the graph — concepts are not loaded as skills.\n" +
	"2. When the task is about impact, dependencies, callers, or \"what breaks if I\n" +
	"   change X\" — OR before you edit any file — query the graph FIRST:\n" +
	"     - If you have the graph tools:  get_context(<file-or-symbol>)\n" +
	"       (also: get_impact, find_symbol)\n" +
	"     - Otherwise, via CLI:           tu-agent graph context <file-or-symbol>\n" +
	"   get_context returns blast radius (dependents), the relevant concept(s),\n" +
	"   conventions, and tests to run — pointers, not source.\n" +
	"3. The graph is authoritative for structure (callers, dependents, tests), but it\n" +
	"   can miss framework/DI/inherited-from-compiled relationships. If it returns\n" +
	"   \"(none)\" where you expect dependents, cross-check with a targeted search\n" +
	"   before concluding.\n" +
	"4. Only then read specific files if you still need detail.\n" +
	"\n" +
	"Do not skip step 2 for impact/dependency questions or before edits — the graph\n" +
	"is cheaper and more complete than re-deriving structure by reading files.\n" +
	"\n" +
	"## MEMORY — recall at start, capture decisions\n" +
	"- At session start call `mem_recent`; before non-trivial work call\n" +
	"  `mem_search <feature area>`. Prior decisions and bug-patterns carry the \"why\"\n" +
	"  the code does not.\n" +
	"- When you make a decision, hit a bug-pattern worth remembering, or finish\n" +
	"  non-trivial work, call `mem_save` with a `decision/...` or `bug-pattern/...`\n" +
	"  topic and a one-paragraph summary. Save the durable \"why\", not session chatter.\n" +
	"- Save a gotcha/trap as its OWN atomic note with type `gotcha` (`mem_save` with\n" +
	"  `type: gotcha`), one trap per note — never as a buried `GOTCHA:`/`OJO:` section\n" +
	"  inside a `decision`/`architecture` note, or it cannot be retrieved as a gotcha.\n" +
	"  Recall all traps with `memory search --type gotcha`.\n" +
	"- Shape note content by type so a future agent can act on it: for\n" +
	"  `bug-pattern`/`gotcha` write Symptom/trigger → Root cause → Fix → Prevention;\n" +
	"  for `decision` write Decision → Why → Alternatives rejected → Scope. Lead with\n" +
	"  the symptom — it makes the note findable by situation, not just by keyword.\n" +
	"- Do NOT hand-list which files a note touches; instead name the code symbols\n" +
	"  (class/type names) in prose — `tu-agent memory relink` derives the file links.\n" +
	"- After `git pull`, run `tu-agent memory import` to absorb teammates' memory\n" +
	"  (chunks under `.tu-agent/memory/chunks/` are shared via git).\n" +
	"\n" +
	"## VERIFY before claiming done\n" +
	"Before reporting work complete, fixed, or passing, run the project's test\n" +
	"command and report the actual result. Evidence before assertions.\n" +
	"\n" +
	"## If the graph looks wrong\n" +
	"If a graph query contradicts what the code plainly shows, the graph may be\n" +
	"stale — run `tu-agent learn` to rebuild, then re-query.\n" +
	knowledgeClose

// upsertMarkedBlock inserts or replaces the region between open/close markers in
// the file at mdPath with body. Idempotent: re-running yields an identical file.
// Creates the file (containing just body) if it does not exist.
func upsertMarkedBlock(mdPath, open, close, body string) error {
	re := regexp.MustCompile(`(?s)` + regexp.QuoteMeta(open) + `.*?` + regexp.QuoteMeta(close))
	existing, err := os.ReadFile(mdPath)
	if err != nil {
		if !os.IsNotExist(err) {
			return fmt.Errorf("upsertMarkedBlock: read %s: %w", mdPath, err)
		}
		if werr := os.WriteFile(mdPath, []byte(body+"\n"), 0o644); werr != nil {
			return fmt.Errorf("upsertMarkedBlock: create %s: %w", mdPath, werr)
		}
		return nil
	}
	var out string
	if re.Match(existing) {
		out = re.ReplaceAllString(string(existing), body)
	} else {
		out = strings.TrimRight(string(existing), "\n") + "\n\n" + body + "\n"
	}
	if err := os.WriteFile(mdPath, []byte(out), 0o644); err != nil {
		return fmt.Errorf("upsertMarkedBlock: write %s: %w", mdPath, err)
	}
	return nil
}

// writeKnowledgeBlock inserts or replaces the tu-agent knowledge-pointer block.
func writeKnowledgeBlock(mdPath string) error {
	return upsertMarkedBlock(mdPath, knowledgeOpen, knowledgeClose, knowledgeBody)
}
