package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/carlosneir4/tu-agent/internal/codegen"
	"github.com/carlosneir4/tu-agent/internal/tdd"
)

// trustStatus is the read-only JSON view of a repo's test-command trust
// decision printed by `tdd trust --check`.
type trustStatus struct {
	Trusted        bool   `json:"trusted"`
	ConfigCommand  string `json:"config_command"`
	AutogenCommand string `json:"autogen_command"`
	Differs        bool   `json:"differs"`
	Reason         string `json:"reason"`
}

// computeTrustStatus resolves the autogen command for root, loads the trust
// store at storePath, runs the trust decision, and fills the struct.
// Differs = configCmd != "" && configCmd != autogen.
func computeTrustStatus(root, configCmd, storePath string) trustStatus {
	auto := codegen.DetectTestCommandForRoot(root)
	store := tdd.LoadStore(storePath)
	trusted, reason := tdd.TestCommandTrust(configCmd, func() string { return auto }, store, root)
	differs := configCmd != "" && configCmd != auto
	return trustStatus{
		Trusted:        trusted,
		ConfigCommand:  configCmd,
		AutogenCommand: auto,
		Differs:        differs,
		Reason:         reason,
	}
}

// trustWarning renders the untrusted warning shown before an interactive
// prompt: it prints configCmd verbatim, names autogenCmd, and includes the
// phrase "not the executables" (trust covers the command TEXT only).
func trustWarning(configCmd, autogenCmd string) string {
	return fmt.Sprintf(`The configured test command differs from the autogenerated one.
  configured: %s
  autogen:    %s
Trusting remembers the command TEXT only, not the executables it invokes
(for example ./gradlew stays under the repo's control).
Trust this command?`, configCmd, autogenCmd)
}

// runTrustCheck marshals st to JSON and prints it to out. It writes nothing to
// disk.
func runTrustCheck(out io.Writer, st trustStatus) error {
	data, err := json.Marshal(st)
	if err != nil {
		return fmt.Errorf("runTrustCheck: marshal: %w", err)
	}
	fmt.Fprintln(out, string(data))
	return nil
}

// runTrustYes remembers configCmd for root: if already trusted it prints a
// "nothing to do" line and does NOT write; otherwise it calls SaveTrust and
// prints a confirmation naming the saved command.
func runTrustYes(out io.Writer, root, configCmd, storePath string) error {
	st := computeTrustStatus(root, configCmd, storePath)
	if st.Trusted {
		fmt.Fprintln(out, "already trusted — nothing to do")
		return nil
	}
	if err := tdd.SaveTrust(root, configCmd); err != nil {
		return fmt.Errorf("tdd trust: %w", err)
	}
	fmt.Fprintf(out, "remembered test command as trusted: %s\n", configCmd)
	return nil
}

// tddTrustCmd is the `tu-agent tdd trust` subcommand. Flags --check and --yes
// select the mode; a bare non-TTY invocation behaves like --check.
var tddTrustCmd = &cobra.Command{
	Use:   "trust",
	Short: "Report and remember trust for the resolved test command",
	RunE: func(cmd *cobra.Command, args []string) error {
		root := repoRoot()
		configCmd := cfg.Tdd.TestCommand
		storePath, err := tdd.TrustPath()
		if err != nil {
			return fmt.Errorf("tdd trust: %w", err)
		}

		yes, _ := cmd.Flags().GetBool("yes")
		check, _ := cmd.Flags().GetBool("check")

		if yes {
			return runTrustYes(cmd.OutOrStdout(), root, configCmd, storePath)
		}
		if check {
			return runTrustCheck(cmd.OutOrStdout(), computeTrustStatus(root, configCmd, storePath))
		}

		// Bare invocation: non-TTY behaves like --check; a TTY prompts.
		isTTY := false
		if f, ok := cmd.InOrStdin().(*os.File); ok {
			if fi, statErr := f.Stat(); statErr == nil && fi.Mode()&os.ModeCharDevice != 0 {
				isTTY = true
			}
		}

		st := computeTrustStatus(root, configCmd, storePath)
		if !isTTY || st.Trusted {
			return runTrustCheck(cmd.OutOrStdout(), st)
		}

		fmt.Fprintln(cmd.OutOrStdout(), trustWarning(configCmd, st.AutogenCommand))
		fmt.Fprint(cmd.OutOrStdout(), "Type 'yes' to trust: ")
		reader := bufio.NewReader(cmd.InOrStdin())
		line, _ := reader.ReadString('\n')
		answer := strings.ToLower(strings.TrimSpace(line))
		if answer != "y" && answer != "yes" {
			return nil
		}
		return runTrustYes(cmd.OutOrStdout(), root, configCmd, storePath)
	},
}

func init() {
	tddTrustCmd.Flags().Bool("check", false, "print the trust status as read-only JSON and exit")
	tddTrustCmd.Flags().Bool("yes", false, "remember the current test command as trusted")
	tddCmd.AddCommand(tddTrustCmd)
}
