package tdd

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Store maps a canonicalized absolute repo path to the sha256 hex of the
// test command the user confirmed for it.
type Store struct {
	entries map[string]string
}

// entry is the on-disk JSON shape for a single repo's trusted command.
type entry struct {
	TestCommandSHA256 string `json:"test_command_sha256"`
}

// HashCommand returns the lowercase sha256 hex of cmd.
func HashCommand(cmd string) string {
	sum := sha256.Sum256([]byte(cmd))
	return hex.EncodeToString(sum[:])
}

// TrustPath returns ~/.tu-agent/trust.json, resolved via os.UserHomeDir.
func TrustPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("tdd.TrustPath: %w", err)
	}
	return filepath.Join(home, ".tu-agent", "trust.json"), nil
}

// canonicalize normalizes root to a single key: absolute path, then the real
// path via EvalSymlinks best-effort. If either step fails, it falls back to the
// best available result so a symlink and its target map to one key.
func canonicalize(root string) string {
	abs, err := filepath.Abs(root)
	if err != nil {
		abs = root
	}
	if resolved, err := filepath.EvalSymlinks(abs); err == nil {
		return resolved
	}
	return abs
}

// LoadStore reads the JSON store at path. It FAILS CLOSED: a missing,
// unreadable, or malformed file yields an empty Store and no error.
func LoadStore(path string) Store {
	empty := Store{entries: map[string]string{}}

	data, err := os.ReadFile(path)
	if err != nil {
		return empty
	}

	var raw map[string]entry
	if err := json.Unmarshal(data, &raw); err != nil {
		return empty
	}

	entries := make(map[string]string, len(raw))
	for root, e := range raw {
		entries[root] = e.TestCommandSHA256
	}
	return Store{entries: entries}
}

// HashFor canonicalizes root and returns the stored sha256 hex for it, or ""
// if none is recorded.
func (s Store) HashFor(root string) string {
	if s.entries == nil {
		return ""
	}
	return s.entries[canonicalize(root)]
}

// TestCommandTrust decides whether cmd is trusted for root. Dependencies are
// injected (autogen func value + Store) so all branches are testable without
// disk or real codegen. Order: 1) empty -> "empty"; 2) cmd == autogen() ->
// "matches autogen"; 3) HashCommand(cmd) matches store.HashFor(root) ->
// "previously confirmed"; else (false, reason naming the autogen command).
func TestCommandTrust(cmd string, autogen func() string, store Store, root string) (trusted bool, reason string) {
	// Trim once so the comparison matches ResolveTestRunner, which runs the
	// trimmed command; SaveTrust trims identically so stored hashes agree.
	cmd = strings.TrimSpace(cmd)
	if cmd == "" {
		return true, "empty"
	}

	auto := autogen()
	if cmd == auto {
		return true, "matches autogen"
	}

	if stored := store.HashFor(root); stored != "" && stored == HashCommand(cmd) {
		return true, "previously confirmed"
	}

	return false, fmt.Sprintf("command differs from autogenerated %q", auto)
}

// SaveTrust canonicalizes root, records HashCommand(cmd) for it, creates
// ~/.tu-agent if absent, and writes the whole store atomically (temp file in
// the same dir + os.Rename). It merges with any existing store so saves for
// other repos are preserved.
func SaveTrust(root, cmd string) error {
	path, err := TrustPath()
	if err != nil {
		return fmt.Errorf("tdd.SaveTrust: %w", err)
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("tdd.SaveTrust: %w", err)
	}

	store := LoadStore(path)
	if store.entries == nil {
		store.entries = map[string]string{}
	}
	store.entries[canonicalize(root)] = HashCommand(strings.TrimSpace(cmd))

	raw := make(map[string]entry, len(store.entries))
	for repo, hexsum := range store.entries {
		raw[repo] = entry{TestCommandSHA256: hexsum}
	}

	data, err := json.MarshalIndent(raw, "", "  ")
	if err != nil {
		return fmt.Errorf("tdd.SaveTrust: %w", err)
	}

	tmp, err := os.CreateTemp(dir, "trust-*.json.tmp")
	if err != nil {
		return fmt.Errorf("tdd.SaveTrust: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return fmt.Errorf("tdd.SaveTrust: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("tdd.SaveTrust: %w", err)
	}

	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("tdd.SaveTrust: %w", err)
	}
	return nil
}
